### PR TITLE
Fix pixelated header image on datasheet

### PR DESCRIPTION
**Pull request by ntzovanis**
Change-type: minor
Signed-off-by: Nicolas Tzovanis <nicolas@resin.io>

### CODE REVIEW

**Comment by dimitrisnl** [comment]
@ntzovanis It would be better to rename your commit as `Fix pixelated header ...`

The resinCI complains with the following error `Error: The commit subject must use the imperative mood`

**Comment by ntzovanis** [comment]
@dimitrisnl can you help me out with this PR. I fixed the commit comment but there's some tests that are still failing.

**Comment by dimitrisnl** [comment]
@ntzovanis 	These tests are not required, `Alpine` tests fail for some reason unknown to me in various repositories.

**Comment by ntzovanis** [comment]
Thanks @dimitrisnl how's the deployment procedure?

**Pull request merged**
